# Generated by Django 4.0.5 on 2022-06-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/about'),
        ),
    ]
