# Generated by Django 4.0.5 on 2022-07-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220702_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
