# Generated by Django 4.0.5 on 2022-07-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_banner_description_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='uploads/avatar'),
        ),
    ]
