# Generated by Django 4.0.5 on 2022-06-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_about_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
