# Generated by Django 4.0.5 on 2022-07-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_user_avatar'),
        ('website', '0005_testimonial'),
    ]

    operations = [
    ]
