# Generated by Django 4.0.5 on 2022-06-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_blog_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_description',
            field=models.TextField(),
        ),
    ]
