# Generated by Django 3.2.13 on 2022-07-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='experts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='running_project',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
