# Generated by Django 3.2.13 on 2022-07-13 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20220713_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='client',
            field=models.IntegerField(blank=True, null=True, default=1, validators=[
                                      django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='home',
            name='experts',
            field=models.IntegerField(blank=True, null=True, validators=[
                                      django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='home',
            name='running_project',
            field=models.IntegerField(blank=True, null=True, validators=[
                                      django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
