# Generated by Django 3.2.13 on 2022-07-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20220714_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='team',
        ),
    ]
