# Generated by Django 3.2.13 on 2022-07-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_team_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='home',
            name='object_id',
        ),
    ]
